### ISSUE TITLE
The username

### ISSUE THREAD

**Issue by lebedev** [angly/DBA#1]
Hi!

It seems like you don't use your GitHub account much. That said, your username is actually the shorter version of mine, and I'd really like to have it. Do you mind giving it to me on some conditions, maybe? Pretty please?

**Comment by angly** [comment]
Hi
Sorry to tell u that i dont wanna to deliver it to u cause some reasons.So, if u want to use the shorter name, u may try to use the other one.
Sorry for that!

**Comment by lebedev** [comment]
Ok, no worries. Sorry for bothering you.
